name: continuous-integration

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
      
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: "test-node-cd"
          environment_name: "test-node-cd"
          region: "ap-southeast-1"
          version_label: "react-demo-new-${{ steps.format-time.outputs.replaced }}"
          deployment_package: deploy.zip
      - name: Deployed!
        run: echo App deployed to ELB